# ======================
# Literals / Enums
# ======================
from typing_extensions import Literal

Genero = Literal["MASCULINO", "FEMENINO", ""]
TipoPersona = Literal["NATURAL", "JURIDICA"]
TipoBien = Literal["BIENES", "ACCIONES Y DERECHOS"]
ClaseBien = Literal["AERONAVES", "CONCESIONES","DERECHOS DE PROPIEAD INTELECTUAL","PREDIOS"
                    ,"MAQUINARIA Y EQUIPOS","MINAS CANTERAS Y DEPOSITOS DE HIDRO","NAVES",
                    "VEHICULOS TERRESTRRES","CREDITOS","OTROS NO ESPECIFICADOS","SIN OBJETOS","PERSONAS JURIDICAS"]

OportunidadPago = Literal[
    "A LA FIRMA DEL CONTRATO/MINUTA",
    "A LA FIRMA DEL ACTA DE TRANSFERENCIA",
    "A LA FIRMA DEL INSTRUMENTO PÚBLICO NOTARIAL PROTOCOLAR",
    "CONTRA LA INSCRIPCIÓN DEL BLOQUEO REGISTRAL",
    "CONTRA LA INSCRIPCIÓN DE LA HIPOTECA",
    "CON LA ENTREGA FÍSICA DEL BIEN",
    "CON ANTERIORIDAD A LA FIRMA DE LA MINUTA",
    "OTRO",
]

MedioPago = Literal[
    "DEPOSITO EN CUENTA",
    "GIRO",
    "TRANSFERENCIA DE FONDOS",
    "ORDEN DE PAGO",
    "TARJETA DE DEBITO",
    "TARJETA DE CREDITO EMITIDA EN EL PAIS",
    "CHEQUE DE GERENCIA",
    "EFECTIVO 008- MENORES A 5000",
    "EFECTIVO 009- EN LOS DEMAS CASOS",
    "MEDIOS DE PAGO USADOS EN COMERCIO EXTERIOR",
    "DOCUMENTOS DE EDPYMES Y COOPERATIVAS DE AHORRO Y CREDITO",
    "TARJETA DE CREDITO EMITIDA O NO EN EL PAIS POR ENT",
    "TARJETAS DE CREDITO EMITIDAS EN EL EXTERIOR POR BA",
    "BIEN MUEBLE",
    "BIEN INMUEBLE",
    "OTROS MEDIOS DE PAGO",
]

FormaPago = Literal[
    "CONTADO",
    "PLAZO",
    "SALDO PENDIENTE DE PAGO",
    "DONACION O ANTICIPO",
    "NO APLICA"
]

DepartamentosPeru = Literal[
    "AMAZONAS", "ANCASH", "APURIMAC", "AREQUIPA", "AYACUCHO", "CAJAMARCA",
    "CALLAO", "CUSCO", "HUANCAVELICA", "HUANUCO", "ICA", "JUNIN",
    "LA LIBERTAD", "LAMBAYEQUE", "LIMA", "LORETO", "MADRE DE DIOS",
    "MOQUEGUA", "PASCO", "PIURA", "PUNO", "SAN MARTIN", "TACNA",
    "TUMBES", "UCAYALI",
]